### PR TITLE
update to SPIP v3.2.11

### PR DESCRIPTION
**Pull request by yalh76**
Package check from a more recent commit where backup script doesn't ask for `root_pwd=$(sudo cat /etc/yunohost/mysql)`

update to SPIP v3.2.11

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Pull request merged**
