### PR TITLE
version 4.2.16

### PR DESCRIPTION
**Pull request by arthurlutz**
## Problem

- Security update

fixes https://github.com/YunoHost-Apps/spip_ynh/issues/74

## Solution

- update version and sha256

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by arthurlutz** [comment]
!testme

**Comment by arthurlutz** [comment]
If anyone comes by here, I am testing it on an existing install that got hacked, is there a way to force overwriting of files ? (eg spip.php still has some added lines after upgrade) and is there way to say "in some folders remove old .php files that are not in the zip used to install" ?

**Comment by tituspijean** [comment]
> If anyone comes by here, I am testing it on an existing install that got hacked, is there a way to force overwriting of files ? (eg spip.php still has some added lines after upgrade) and is there way to say "in some folders remove old .php files that are not in the zip used to install" ?

Checkout the `full_replace` and `keep` flags of https://yunohost.org/fr/packaging_apps_helpers#ynh-setup-source

**Comment by orhtej2** [comment]
Superseded by #76

**Pull request closed without merging**
