### PR TITLE
Update to spip 4.0.0

### PR DESCRIPTION
**Pull request by pp-r**
## Problem

- *A new version is available*

## Solution

- *Update to 4.0.0 - https://www.spip.net/fr_download#SPIP-4-0-0-8-juillet-2021*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by pp-r** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
thank you!

**Comment by kay0u** [comment]
!testme

**Pull request merged**
